apiVersion: apps/v1
kind: Deployment
metadata:
  name: club-backend-${ENV}
  labels:
    app: club-backend
    env: ${ENV}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: club-backend
      env: ${ENV}
  template:
    metadata:
      labels:
        app: club-backend
        env: ${ENV}
    spec:
      containers:
      - name: club
        image: docker.pedanticorderliness.com/club-backend:${TAG_NAME}
        ports:
        - containerPort: 3000
        env:
        - name: ENV
          value: ${ENV}
      imagePullSecrets:
        - name: regcred
